---
#- name: Install epel-release
#  yum:
#    name: epel-release
#    state: latest

#- name: Disable firewalld
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: no
#  ignore_errors: yes

#- name: Disable SeLinux
#  ansible.posix.selinux:
#    state: disabled

- name: reload network centralServer
  service:
    name: network
    state: restarted
  when: (ansible_hostname == "centralServer")

- name: set up route on office1Server
  template:
    src: office1Server_route.j2
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
    mode: 0755
  notify: netplan apply
  when: (ansible_hostname == "office1Server")

- name: set up route on office2Server
  template:
    src: office2Server_route.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0755
  notify: restart networking
  when: (ansible_hostname == "office2Server")

#- name: Reboot office2Server
#  reboot:
#    reboot_timeout: 3600
#  when: (ansible_hostname == "office2Server")
...
